let initializeApp,getAuth,GoogleAuthProvider,createUserWithEmailAndPassword,signInWithEmailAndPassword,signInWithPopup,signOut,onAuthStateChanged,updateProfile,getFirestore,doc,getDoc,setDoc,updateDoc,collection,onSnapshot,query,orderBy,limit;
const firebaseConfig=window.FRC115FirebaseConfig||{};

const arcs=[
 {n:'01',title:'Start Here',time:'2 sessions',xp:80,intro:'What FRC software does, how Team 115 works, and the habits that keep people safe.',read:`<h4>Software is the bridge between intent and motion.</h4><p>Every 20 milliseconds, our robot reads sensors, decides what to do, and commands hardware. Good robot code is safe, measurable, and understandable — especially at 2 AM in the pit.</p><p>Start with Java basics, Git branches, the Driver Station, and simulation. Our first naming rule: values carry units. <code>height_m</code> is never confused with rotations.</p>`,build:`<h4>Build: make your first meaningful change.</h4><p>Create a branch, find a constant that needs a unit suffix, and rename it. Run a build. Describe why the rename prevents a specific mistake in your pull request.</p>`,check:'Fill in the unit suffix: <code>MAX_HEIGHT___ = 1.45</code>',answer:'_m',note:'Correct — this is a measurement in meters.'},
 {n:'02',title:'Robot Fundamentals',time:'3 sessions',xp:100,intro:'The roboRIO, CAN bus, periodic loops, motors, sensors, and simulation.',read:`<h4>A robot is a timed control system.</h4><p>Code runs repeatedly: read current inputs, choose a behavior, then send outputs. Learn the physical path of a command: driver → roboRIO → CAN → controller → mechanism → sensor → roboRIO.</p><p>Simulation is an early warning system. It lets us exercise the same mechanism API before wiring is ready.</p>`,build:`<h4>Build: trace a signal.</h4><p>Pick a sensor used on the robot. Draw its data path to the subsystem and find where its value is logged. In sim, change the input and explain the resulting output.</p>`,check:'What is the safe order of a periodic loop?',answer:'inputs handle outputs',note:'Yes: inputs → handle → outputs.'},
 {n:'03',title:'Java for Robots',time:'3 sessions',xp:100,intro:'Classes, enums, interfaces, constructors, collections, and APIs that reveal intent.',read:`<h4>Make illegal behavior hard to express.</h4><p>Use enums for a finite set of commands. Use interfaces for contracts. Use method names such as <code>home()</code> and <code>trackToHeight()</code> so callers request behavior instead of manipulating implementation.</p>`,build:`<h4>Build: name a behavior.</h4><p>Write a public Command enum and three intention-revealing API methods for a fictional intake. Explain why callers never need its internal substate.</p>`,check:'Which API is clearer: <code>home()</code> or <code>setState(3)</code>?',answer:'home()',note:'Exactly. The method tells the caller what it requests.'},
 {n:'04',title:'Our Architecture',time:'3 sessions',xp:120,intro:'The manual periodic order, singletons, AdvantageKit, and REAL / SIM / REPLAY modes.',read:`<h4>The robot loop is a deliberate conversation.</h4><p>26DropTop does not use the standard command scheduler. <code>Robot.robotPeriodic()</code> explicitly runs controls, the superstructure, mechanisms, drive, and vision. This preserves predictable data flow.</p><div class="code-block">controls.update();<br>superstructure.periodic();<br>elevator.periodic();<br>tracking.periodic();<br>drive.periodic();<br>vision.periodic();</div><p>Subsystems are singletons; each physical mechanism has one authoritative owner. <code>Constants.currentMode</code> selects real IO, simulation IO, or replay behavior.</p>`,build:`<h4>Build: map the loop.</h4><p>Open <code>Robot.java</code>. Label each periodic call as request, coordination, mechanism, localization, or actuation. Then explain why Controls runs before SS.</p>`,check:'Which layer should turn a button press into a request?',answer:'controlscheme',note:'Correct. ControlScheme translates operator input into named requests.'},
 {n:'05',title:'IO & Devices',time:'4 sessions',xp:140,intro:'The wrapper, config, IO interface, real implementation, and simulation implementation.',read:`<h4>Hardware is an implementation detail.</h4><p>Reusable hardware lives in <code>frc.robot.devices.&lt;device&gt;</code>. A public wrapper owns IO choice and logging; an IO interface defines inputs and commands; real and sim classes implement the contract.</p><p>The mechanism calls <code>readInputs()</code> once in input processing. The wrapper calls <code>Logger.processInputs(...)</code>. Vendor objects stay below the boundary.</p>`,build:`<h4>Build: finish an IOReal class.</h4><p>Create <code>CANrangeIOReal</code>. Update its AutoLogged inputs with connected state and distance in meters. Do not expose vendor objects outside this file.</p>`,check:'Where should vendor motor-controller objects live?',answer:'ioreal',note:'Right — keep implementation-specific objects in IOReal.'},
 {n:'06',title:'Commands & Substates',time:'4 sessions',xp:150,intro:'Build safe mechanisms with command enums, staged substates, timers, and deterministic idle behavior.',read:`<h4>Commands describe intent. Substates describe progress.</h4><p>New mechanisms extend <code>SubsystemBase&lt;Command&gt;</code>. Public commands — HOMING, GO_TO_HEIGHT, MANUAL — describe what callers want. Private substates describe the mechanism’s progress.</p><div class="code-block">if (firstLoop()) setSubstate(Travel.MOVING);<br>motor.setMotionMagic(targetHeight_m);<br>if (atTarget(TOLERANCE_m))<br>&nbsp;&nbsp;setSubstate(Travel.HOLDING);</div><p>Set safe, deterministic outputs in IDLE and DISABLED. State and target values must be logged so a pit log has a complete story.</p>`,build:`<h4>Build: a wrist subsystem.</h4><p>Add Wrist.java with IDLE, HOMING, GO_TO_ANGLE, and MANUAL. GO_TO_ANGLE needs MOVING and HOLDING substates. Add IO real and sim, then log targetAngle_deg and zeroed.</p>`,check:'What resets when you call setSubstate(...) ?',answer:'substatetimer',note:'Correct. The substate timer resets so staged behavior is observable.'},
 {n:'07',title:'Coordination & Control',time:'3 sessions',xp:120,intro:'Superstructure flags, OI translation, priority, and safe integrated behavior.',read:`<h4>Buttons request; the superstructure decides.</h4><p>ControlScheme converts OI into named inputs and flags. SS owns coordination and priority. Mechanisms own their local safety and closed-loop details. This lets autonomous, buttons, and test code use the same behavior.</p>`,build:`<h4>Build: give SS a new request.</h4><p>Add a named flag for your wrist goal. Map a button in ControlScheme. Make SS select a safe command using its priority chain, then log the selected behavior.</p>`,check:'Who owns mechanism coordination and priority?',answer:'ss',note:'Yes. SS chooses the coordinated high-level action.'},
 {n:'08',title:'Pose, Vision & Tracking',time:'5 sessions',xp:180,intro:'Odometry, AprilTags, Limelight observations, fusion, filtering, and target tracking.',read:`<h4>Vision corrects a belief — it does not replace one.</h4><p>Our Vision subsystem rejects implausible observations, inverse-variance fuses accepted Limelight poses, predicts from odometry, filters the correction, then hands the result to Drive.</p><div class="code-block">reject observation <i>→</i> fuse measurements <i>→</i> filter pose <i>→</i> drive.addVisionMeasurement(...)</div><p>Tune with evidence. Inspect accepted observations, timestamps, ambiguity, standard deviations, and pose in AdvantageScope before touching constants.</p>`,build:`<h4>Build: reject a bad pose.</h4><p>Add one logged rejection condition to <code>Vision.shouldReject()</code>. Test it in sim or replay, then document when the condition could reject a useful frame.</p>`,check:'What should run between raw observations and Drive pose correction?',answer:'filter',note:'Correct. The filter uses odometry prediction and vision correction.'}
];
let db=null,auth=null,currentUser=null,leaderboardUnsubscribe=null,profile={points:0,completed:[],streak:0,lastActive:'',displayName:'Guest'};
const demoLeaders=[['Avery M.',1140],['Jordan K.',980],['Morgan T.',810],['Riley C.',650],['Casey P.',540]];
const isConfigured=()=>firebaseConfig.apiKey && !firebaseConfig.apiKey.includes('PASTE_');
async function initFirebase(){if(!isConfigured()){loadDemoProfile();return;}try{const [appSdk,authSdk,storeSdk]=await Promise.all([import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js')]);({initializeApp}=appSdk);({getAuth,GoogleAuthProvider,createUserWithEmailAndPassword,signInWithEmailAndPassword,signInWithPopup,signOut,onAuthStateChanged,updateProfile}=authSdk);({getFirestore,doc,getDoc,setDoc,updateDoc,collection,onSnapshot,query,orderBy,limit}=storeSdk);const app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);onAuthStateChanged(auth,async user=>{currentUser=user;if(user){await loadProfile();}else{profile={points:0,completed:[],streak:0,lastActive:'',displayName:'Guest'};}renderAll();});}catch(error){console.warn('Firebase did not load; using interactive demo mode.',error);loadDemoProfile();}}
let selected=3,tab='read';
const $=id=>document.getElementById(id);
function renderAll(){renderDashboard();renderRoadmap();renderLesson();renderLeaders();}
function renderDashboard(){const done=profile.completed||[];$('pointsValue').textContent=profile.points||0;$('streakValue').textContent=profile.streak||0;$('lessonsValue').textContent=`${done.length} / 8`;$('progressValue').textContent=`${Math.round(done.length/8*100)}%`;$('nextArc').textContent=arcs.find((_,i)=>!done.includes(i))?.title||'All arcs complete!';$('welcomeText').textContent=currentUser?`Welcome back, ${profile.displayName}. Your progress is saved and your team can see your momentum.`:'Log in to save your work, build a streak, and climb the Team 115 leaderboard.';$('authButton').textContent=currentUser?'Log out':'Log in';$('dashboardAuth').textContent=currentUser?'Log out':'Create your account';}
function renderRoadmap(){$('roadmap').innerHTML=arcs.map((a,i)=>`<button class="roadmap-item ${i===selected?'active':''} ${profile.completed?.includes(i)?'complete':''}" data-i="${i}"><span class="arc-state">${profile.completed?.includes(i)?'✓':a.n}</span><div><small>ARC ${a.n}</small><b>${a.title}</b></div></button>`).join('');document.querySelectorAll('.roadmap-item').forEach(x=>x.onclick=()=>{selected=+x.dataset.i;tab='read';renderRoadmap();renderLesson();});}
function renderLesson(){const a=arcs[selected];$('lessonLabel').textContent=`ARC ${a.n}`;$('lessonTime').textContent=a.time;$('lessonXp').textContent=`${a.xp} XP`;$('lessonTitle').textContent=a.title;$('lessonIntro').textContent=a.intro;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));let body=tab==='read'?`<div class="lesson-detail">${a.read}</div>`:tab==='build'?`<div class="lesson-detail">${a.build}<p><strong>Mentor review:</strong> Bring a simulation screenshot or log trace and your branch link.</p></div>`:`<div class="lesson-detail"><div class="check-card"><span>QUICK CHECK</span><b>${a.check}</b><div class="check-row"><input id="checkInput" placeholder="Your answer"><button id="checkButton">Check</button></div><p class="check-feedback" id="checkFeedback"></p></div></div>`;$('lessonBody').innerHTML=body;if(tab==='check')$('checkButton').onclick=()=>{$('checkFeedback').textContent=$('checkInput').value.trim().toLowerCase()===a.answer?a.note:'Try again. Use the reading and consider the Team 115 boundary names.';};$('completeButton').textContent=profile.completed?.includes(selected)?'Arc complete ✓':`Complete arc +${a.xp} XP`;}
document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>{tab=x.dataset.tab;renderLesson();});
async function completeArc(){if(!currentUser){openAuth();return;}if(profile.completed.includes(selected))return;profile.completed=[...profile.completed,selected];profile.points+=arcs[selected].xp;profile.streak=calculateStreak(profile.lastActive);profile.lastActive=new Date().toISOString().slice(0,10);if(db){await updateDoc(doc(db,'users',currentUser.uid),{points:profile.points,completed:profile.completed,streak:profile.streak,lastActive:profile.lastActive});}else{saveDemoProfile();}renderAll();}
function calculateStreak(last){const today=new Date();const key=today.toISOString().slice(0,10);if(last===key)return profile.streak||1;const yesterday=new Date(today-86400000).toISOString().slice(0,10);return last===yesterday?(profile.streak||0)+1:1;}
$('completeButton').onclick=completeArc;$('nextLesson').onclick=()=>{selected=(selected+1)%arcs.length;tab='read';renderRoadmap();renderLesson();};
function renderLeaders(){const holder=$('leaderboardList');if(!db){const rows=(currentUser?[[profile.displayName,profile.points],...demoLeaders]:demoLeaders).sort((a,b)=>b[1]-a[1]).slice(0,10);holder.innerHTML=rows.map((x,i)=>leaderRow(i+1,x[0],x[1])).join('');const rank=rows.findIndex(x=>x[0]===profile.displayName);$('rankValue').textContent=rank>=0?`#${rank+1}`:'—';$('leaderboardStatus').textContent=currentUser?'Local demo profile':'Demo board';return;}if(leaderboardUnsubscribe)return;$('leaderboardStatus').textContent='Loading live board…';const q=query(collection(db,'users'),orderBy('points','desc'),limit(10));leaderboardUnsubscribe=onSnapshot(q,snap=>{const rows=snap.docs.map(d=>[d.data().displayName||'Team member',d.data().points||0]);holder.innerHTML=(rows.length?rows:demoLeaders).map((x,i)=>leaderRow(i+1,x[0],x[1])).join('');const rank=rows.findIndex(x=>x[0]===profile.displayName);$('rankValue').textContent=rank>=0?`#${rank+1}`:'—';$('leaderboardStatus').textContent='Live from Firebase';},()=>{$('leaderboardStatus').textContent='Demo board';});}
function leaderRow(rank,name,points){return `<li><span class="rank ${rank<4?'top':''}">#${rank}</span><span class="person"><i class="avatar">${name.slice(0,1)}</i>${name}</span><span class="leader-progress"><span style="width:${Math.min(100,points/12)}%"></span></span><b class="leader-points">${points} XP</b></li>`;}
async function loadProfile(){const ref=doc(db,'users',currentUser.uid),snap=await getDoc(ref);if(snap.exists()){profile={...profile,...snap.data()};}else{profile={points:0,completed:[],streak:1,lastActive:new Date().toISOString().slice(0,10),displayName:currentUser.displayName||currentUser.email.split('@')[0]};await setDoc(ref,{...profile,uid:currentUser.uid,createdAt:new Date().toISOString()});}}
function loadDemoProfile(){try{const saved=JSON.parse(localStorage.getItem('frc115-demo-profile'));if(saved){currentUser={uid:'local-demo'};profile=saved;}}catch{}renderAll();}
function saveDemoProfile(){localStorage.setItem('frc115-demo-profile',JSON.stringify(profile));}
function logout(){if(auth){signOut(auth);return;}currentUser=null;profile={points:0,completed:[],streak:0,lastActive:'',displayName:'Guest'};renderAll();}
function showView(view){document.querySelectorAll('.app-view').forEach(section=>section.hidden=section.dataset.view!==view);document.querySelectorAll('.nav-view[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});}
const modal=$('authModal');let signup=false;function openAuth(){if(!isConfigured()){$('authError').textContent='Add your Firebase project values in firebase-config.js to enable accounts.';}modal.showModal();}function setMode(next){signup=next;$('authEyebrow').textContent=signup?'JOIN THE ACADEMY':'WELCOME BACK';$('authTitle').textContent=signup?'Start your software journey.':'Log in to your academy.';$('nameLabel').style.display=signup?'grid':'none';$('submitAuth').innerHTML=signup?'Create account <span>→</span>':'Log in <span>→</span>';$('authSwitch').innerHTML=signup?'Already have an account? <button type="button" id="switchMode">Log in</button>':'New to the team? <button type="button" id="switchMode">Create an account</button>';$('switchMode').onclick=()=>setMode(!signup);}
setMode(false);document.querySelectorAll('.nav-view[data-view]').forEach(button=>button.onclick=()=>showView(button.dataset.view));showView('home');$('joinButton').onclick=openAuth;$('beginButton').onclick=()=>currentUser?showView('courses'):openAuth();$('panelStart').onclick=()=>showView('courses');$('dashboardResume').onclick=()=>showView('courses');$('missionButton').onclick=()=>{selected=5;tab='build';renderRoadmap();renderLesson();showView('courses');};$('dashboardAuth').onclick=()=>currentUser?logout():openAuth();$('authButton').onclick=()=>currentUser?logout():openAuth();$('closeModal').onclick=()=>modal.close();
$('authForm').onsubmit=async e=>{e.preventDefault();if(!db){const name=$('nameInput').value.trim()||$('emailInput').value.split('@')[0]||'Team 115 Member';currentUser={uid:'local-demo'};profile={points:profile.points||0,completed:profile.completed||[],streak:profile.streak||1,lastActive:profile.lastActive||new Date().toISOString().slice(0,10),displayName:name};saveDemoProfile();renderAll();modal.close();return;}$('authError').textContent='';try{let cred;if(signup){cred=await createUserWithEmailAndPassword(auth,$('emailInput').value,$('passwordInput').value);await updateProfile(cred.user,{displayName:$('nameInput').value.trim()||'Team 115 Member'});currentUser=cred.user;await loadProfile();}else{cred=await signInWithEmailAndPassword(auth,$('emailInput').value,$('passwordInput').value);}modal.close();}catch(err){$('authError').textContent=err.message.replace('Firebase: ','');}};
$('googleAuth').onclick=async()=>{if(!db){currentUser={uid:'local-demo'};profile={points:profile.points||0,completed:profile.completed||[],streak:profile.streak||1,lastActive:profile.lastActive||new Date().toISOString().slice(0,10),displayName:'Google Demo Member'};saveDemoProfile();renderAll();modal.close();return;}try{await signInWithPopup(auth,new GoogleAuthProvider());modal.close();}catch(err){$('authError').textContent=err.message.replace('Firebase: ','');}};
initFirebase();
